language: r
sudo: required
cache: packages

r:
  - devel
  - release
  
before_install:
  - make dna
  - cp ./output/dna-*.jar ./rDNA/tests/testthat/
  - cd rDNA

addons:
  apt:
    packages:
       - default-jdk
       - r-cran-rjava
       - libudunits2-dev
       - r-cran-mcmcpack
       
r_packages:
  - devtools

r_github_packages:  
  - igraph/rigraph
  
script:
  - Rscript -e "install.packages(c('rJava', 'ggraph'))" # Some packages need to be installed for every R version
  - R CMD build .
  - R CMD check *tar.gz

after_success:
    - Rscript -e 'covr::codecov()'
