language: java
jdk:
  - oraclejdk8

before_script:
  - cd DNA
  
script: ant build

deploy:
  provider: releases
  api_key: "$GH_Token"
  file: "/home/travis/build/JBGruber/dna/DNA/bin/DNA beta 21.jar"
  skip_cleanup: true
  on:
    tags: true

